name: Deploy to HuggingFace

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_OUTREACH_TOKEN }}
        run: |
          git config user.email "deploy@github.com"
          git config user.name "GitHub Deploy"
          git remote add hf https://brahmacarvaka:$HF_TOKEN@huggingface.co/spaces/brahmacarvaka/SmartCoverLetter
          git push hf main --force
